import { createHash } from 'node:crypto';
import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { describe, expect, it } from 'vitest';
import { deferFacilityDatePaths, invalidationPaths, planDeployment } from './deploy-content.mjs';
import { onlySourceCheckDatesChanged } from './facility-date-only.mjs';

describe('content deployment plan', () => {
  it('skips invalidation when generated bytes are unchanged', () => {
    expect(planDeployment({ 'index.html': 'a' }, { 'index.html': 'a' })).toEqual({ changed: [], removed: [], paths: [] });
  });

  it('defers date-only page invalidation while retaining availability freshness', () => {
    const before = [{ id: 'track', sources: [{ url: 'https://official.example', verifiedAt: '2026-08-24' }], individualUse: { status: 'available' } }];
    const after = structuredClone(before);
    after[0].sources[0].verifiedAt = '2026-09-26';
    expect(onlySourceCheckDatesChanged(before, after)).toBe(true);
    after[0].individualUse.status = 'unavailable';
    expect(onlySourceCheckDatesChanged(before, after)).toBe(false);
    const plan = planDeployment(
      { 'index.html': 'old', 'availability/manifest.json': 'old' },
      { 'index.html': 'new', 'availability/manifest.json': 'new' },
    );
    expect(deferFacilityDatePaths(plan, true).paths).toEqual(['/availability/manifest.json']);
    expect(deferFacilityDatePaths(plan, true).deferredPaths).toEqual(['/', '/index.html']);
  });

  it('maps rewritten HTML shells, dated data and the service worker to viewer URLs', () => {
    expect(invalidationPaths([
      'index.html', 'en/index.html', 'tracks/example/index.html',
      'data/availability/2026-09-24.json', 'service-worker.js',
    ])).toEqual([
      '/', '/data/availability/2026-09-24.json', '/en/', '/en/index.html',
      '/index.html', '/service-worker.js', '/tracks/example', '/tracks/example/',
      '/tracks/example/index.html',
    ]);
  });

  it('includes removed URLs and leaves unrelated pages out', () => {
    const plan = planDeployment(
      { 'privacy/index.html': 'old', 'about/index.html': 'same' },
      { 'about/index.html': 'same' },
    );
    expect(plan).toEqual({ changed: [], removed: ['privacy/index.html'],
      paths: ['/privacy', '/privacy/index.html'] });
  });

  it('keeps old immutable assets available to already-open pages', () => {
    expect(planDeployment({ 'assets/index-old.js': 'old' }, {})).toEqual({ changed: [], removed: [], paths: [] });
    expect(planDeployment({}, { 'assets/index-new.js': 'new' })).toEqual({ changed: ['assets/index-new.js'], removed: [], paths: [] });
    expect(planDeployment({ 'assets/index.js': 'old' }, { 'assets/index.js': 'new' }).paths).toEqual(['/assets/index.js']);
  });

  it('limits a daily 31-day refresh to one availability-only wildcard', () => {
    const dates = Array.from({ length: 31 }, (_, index) =>
      `${new Date(Date.UTC(2026, 8, index + 1)).toISOString().slice(0, 10)}.json`);
    const files = ['availability/manifest.json', ...dates.map(date => `availability/${date}`)];
    const previous = Object.fromEntries(files.map(key => [key, 'old']));
    const current = Object.fromEntries(files.map(key => [key, 'new']));
    expect(planDeployment(previous, current).paths).toEqual(['/availability/*']);
    expect(invalidationPaths(['availability/2026-09-24.json'])).toEqual(['/availability/2026-09-24.json']);
  });

  it('groups a complete track-shell rollout but keeps one changed facility precise', () => {
    const shellKeys = Array.from({ length: 12 }, (_, index) => `tracks/facility-${index}/index.html`);
    const before = Object.fromEntries(shellKeys.map(key => [key, 'old']));
    const after = Object.fromEntries(shellKeys.map(key => [key, 'new']));
    expect(planDeployment(before, after).paths).toEqual(['/tracks/*']);
    expect(planDeployment(before, { ...before, [shellKeys[0]]: 'new' }).paths).toEqual([
      '/tracks/facility-0', '/tracks/facility-0/', '/tracks/facility-0/index.html',
    ]);
  });

  it('does not call CloudFront or rewrite S3 on a no-change scheduled deploy', () => {
    const root = mkdtempSync(join(tmpdir(), 'itsrun-deploy-test-'));
    try {
      const bin = join(root, 'bin');
      const dist = join(root, 'dist');
      mkdirSync(bin);
      mkdirSync(dist);
      mkdirSync(join(dist, 'assets'));
      writeFileSync(join(dist, 'index.html'), '<html>same</html>');
      writeFileSync(join(dist, 'service-worker.js'), 'self.skipWaiting()');
      const files = Object.fromEntries(['index.html', 'service-worker.js'].map(key => [key,
        createHash('sha256').update(readFileSync(join(dist, key))).digest('hex')]));
      const source = join(root, 'previous.json');
      writeFileSync(source, JSON.stringify({ version: 1, files }));
      const log = join(root, 'aws.log');
      writeFileSync(join(bin, 'aws'), `#!/bin/sh\nprintf '%s\\n' "$*" >> "$FAKE_AWS_LOG"\nif [ "$1 $2" = 's3api get-object' ]; then cp "$FAKE_AWS_MANIFEST" "$7"; fi\n`);
      chmodSync(join(bin, 'aws'), 0o755);
      const result = spawnSync('node', [new URL('./deploy-content.mjs', import.meta.url).pathname, 'bucket', 'distribution'], {
        cwd: root,
        env: { ...process.env, PATH: `${bin}:${process.env.PATH}`, FAKE_AWS_LOG: log, FAKE_AWS_MANIFEST: source },
        encoding: 'utf8',
      });
      expect(result.status, result.stderr).toBe(0);
      expect(result.stdout).toContain('CloudFront: 0 paths (skipped)');
      expect(readFileSync(log, 'utf8').trim().split('\n')).toHaveLength(1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, 30_000);

  it('uploads date-only content without creating a CloudFront invalidation', () => {
    const root = mkdtempSync(join(tmpdir(), 'itsrun-date-deploy-'));
    try {
      const bin = join(root, 'bin');
      const dist = join(root, 'dist');
      mkdirSync(bin);
      mkdirSync(dist);
      writeFileSync(join(dist, 'index.html'), '<html>new date</html>');
      writeFileSync(join(dist, 'service-worker.js'), 'self.skipWaiting()');
      const previous = {
        'index.html': createHash('sha256').update('<html>old date</html>').digest('hex'),
        'service-worker.js': createHash('sha256').update('self.skipWaiting()').digest('hex'),
      };
      const source = join(root, 'previous.json');
      writeFileSync(source, JSON.stringify({ version: 1, files: previous }));
      const log = join(root, 'aws.log');
      writeFileSync(join(bin, 'aws'), `#!/bin/sh\nprintf '%s\\n' "$*" >> "$FAKE_AWS_LOG"\nif [ "$1 $2" = 's3api get-object' ]; then cp "$FAKE_AWS_MANIFEST" "$7"; fi\n`);
      chmodSync(join(bin, 'aws'), 0o755);
      const result = spawnSync('node', [new URL('./deploy-content.mjs', import.meta.url).pathname, 'bucket', 'distribution'], {
        cwd: root,
        env: { ...process.env, PATH: `${bin}:${process.env.PATH}`, FAKE_AWS_LOG: log,
          FAKE_AWS_MANIFEST: source, ITSRUN_DEFER_FACILITY_DATE_INVALIDATION: 'true' },
        encoding: 'utf8',
      });
      expect(result.status, result.stderr).toBe(0);
      expect(result.stdout).toContain('2 date-only paths deferred');
      const calls = readFileSync(log, 'utf8');
      expect(calls).toContain('s3 cp');
      expect(calls).not.toContain('cloudfront create-invalidation');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, 30_000);

  it('migrates the prior S3 content and invalidates only an updated service worker', () => {
    const root = mkdtempSync(join(tmpdir(), 'itsrun-deploy-migrate-'));
    try {
      const bin = join(root, 'bin');
      const dist = join(root, 'dist');
      const snapshot = join(root, 'snapshot');
      for (const directory of [bin, dist, snapshot, join(dist, 'assets')]) mkdirSync(directory);
      writeFileSync(join(dist, 'index.html'), '<html>same</html>');
      writeFileSync(join(snapshot, 'index.html'), '<html>same</html>');
      writeFileSync(join(dist, 'service-worker.js'), 'new worker');
      writeFileSync(join(snapshot, 'service-worker.js'), 'old worker');
      const log = join(root, 'aws.log');
      writeFileSync(join(bin, 'aws'), `#!/bin/sh\nprintf '%s\\n' "$*" >> "$FAKE_AWS_LOG"\ncase "$1 $2" in\n  's3api get-object') echo 'NoSuchKey' >&2; exit 1;;\n  's3 sync') cp -R "$FAKE_AWS_SNAPSHOT/." "$4/";;\n  'cloudfront create-invalidation') echo I123;;\n  'cloudfront get-invalidation') echo Completed;;\nesac\n`);
      chmodSync(join(bin, 'aws'), 0o755);
      const result = spawnSync('node', [new URL('./deploy-content.mjs', import.meta.url).pathname, 'bucket', 'distribution'], {
        cwd: root,
        env: { ...process.env, PATH: `${bin}:${process.env.PATH}`, FAKE_AWS_LOG: log, FAKE_AWS_SNAPSHOT: snapshot },
        encoding: 'utf8',
      });
      expect(result.status, result.stderr).toBe(0);
      expect(result.stdout).toContain('CloudFront: 1 paths');
      const calls = readFileSync(log, 'utf8');
      expect(calls).toContain('cloudfront create-invalidation --distribution-id distribution --paths /service-worker.js');
      expect(calls).not.toContain('--paths /index.html');
      expect(calls).toContain('s3 cp');
      expect(calls).toContain('.itsrun-deploy/manifest-v1.json');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, 30_000);
});
