export const paceCopy = {
  ja: {
    title: 'マラソンペース表', intro: '目標タイムから、自分のペースと通過タイムをすぐ確認。',
    input: '計算方法', byGoal: '目標タイムから', byPace: '1kmペースから', goal: '目標タイム', pace: '1kmのペース',
    hours: '時間', minutes: '分', seconds: '秒', goalRange: '1時間00分00秒〜12時間00分00秒。分・秒は0〜59で入力してください。',
    paceRange: '1kmあたり2分00秒〜20分00秒。秒は0〜59で入力してください。', presets: '目標タイムの候補',
    remember: '設定はこのブラウザに保存され、次回も表示されます。', storageFailed: 'このブラウザでは設定を保存できません。リンクを保存すると同じ表を開けます。',
    reset: '設定をリセット', invalidLink: 'リンクの設定を読み取れなかったため、前回の設定または4時間の表を表示しています。',
    results: '計算結果', finish: 'ゴール', half: 'ハーフ', approx: '秒単位に四捨五入した目安', splits: '自分の通過タイム', distance: '距離', elapsed: 'スタートからの時間',
    rounding: '42.195kmを一定ペースで走る計算です。通過時間は元の値から計算し、1秒未満を切り捨てています。表示した1kmペースの積み上げとは数秒ずれる場合があります。',
    subNote: '4時間ちょうどの計算はサブ4とは異なります。4時間を切りたい場合は、3時間59分などの目標に変更してください。',
    share: 'リンクをコピー', image: '画像で保存', saving: '画像を作成中…', copied: 'この設定のリンクをコピーしました。',
    manualCopy: 'リンクを選択してコピーしてください。', imageSaved: '画像のダウンロードを開始しました。', imageFailed: '画像を保存できませんでした。もう一度お試しください。',
    imageNote: '一定ペース・通過時間は1秒未満切り捨て。ペースは四捨五入。',
    training: '練習での所要時間', trainingIntro: '同じペースで走るときの目安。400mトラックの1周や、ペース走の確認に。',
    findTrack: '練習するトラックを探す', compare: '目標タイムを比較する', compareHint: '2時間〜6時間30分の一覧表。スマホでは横にスクロールできます。',
    invalidInput: '入力を確認してください。有効な時間を入力すると、通過タイムが表示されます。',
  },
  en: {
    title: 'Marathon pace table', intro: 'Your goal, your pace. Check your personal splits in seconds.',
    input: 'Calculation method', byGoal: 'From finish time', byPace: 'From pace per km', goal: 'Goal finish time', pace: 'Pace per km',
    hours: 'Hours', minutes: 'Minutes', seconds: 'Seconds', goalRange: 'Enter 1:00:00–12:00:00. Minutes and seconds must be 0–59.',
    paceRange: 'Enter 2:00–20:00 per km. Seconds must be 0–59.', presets: 'Suggested finish times',
    remember: 'Your settings are saved in this browser for your next visit.', storageFailed: 'This browser cannot save settings. Save the link to reopen this plan.',
    reset: 'Reset settings', invalidLink: 'The link settings were invalid. Showing your previous settings or the four-hour default.',
    results: 'Results', finish: 'Finish', half: 'Half marathon', approx: 'Approximate pace, rounded to the nearest second', splits: 'Your split times', distance: 'Distance', elapsed: 'Elapsed time',
    rounding: 'Calculated at a constant pace over 42.195 km. Elapsed times use unrounded values and are truncated to whole seconds. Multiplying the displayed pace may give slightly different times.',
    subNote: 'An exact four-hour finish is not sub-4. Set a faster goal, such as 3:59:00, if you want to finish under four hours.',
    share: 'Copy link', image: 'Save image', saving: 'Creating image…', copied: 'Link to this plan copied.', manualCopy: 'Select and copy this link.',
    imageSaved: 'Image download started.', imageFailed: 'Could not save the image. Please try again.', imageNote: 'Constant pace. Elapsed times truncated; pace rounded to whole seconds.',
    training: 'Training times', trainingIntro: 'Times at this pace for a track lap or a steady run.', findTrack: 'Find a track for your run',
    compare: 'Compare finish times', compareHint: 'Browse goals from 2:00 to 6:30. Scroll sideways on a phone.',
    invalidInput: 'Check your input. Enter a valid time to see your splits.',
  },
} as const;
