export const PARSER_VERSION = '1.0.0';

export const sourceUrls = {
  hikarigaoka: 'https://www.tokyo-park.or.jp/park/hikarigaoka/news/2026/trackfield_2026_8_1.html',
  musashino: 'https://www.musashino.or.jp/sports/kaihou/index.html',
  tokyoGymnasium: 'https://www.tef.or.jp/tmg/opening.html',
  oizumi: 'https://www.tokyo-park.or.jp/park/oizumi-chuo/facility/',
  akatsuka: 'https://www.tokyo-park.or.jp/park/akatsuka/facility/',
  inokashira: 'https://www.kensetsu.metro.tokyo.lg.jp/jimusho/seibuk/inokashira/shinsei',
  asaka: 'https://www.city.asaka.lg.jp/soshiki/41/chuourikujou.html',
  yoyogi: 'https://www.tokyo-park.or.jp/park/yoyogi/facility/',
  nerima: 'https://www.city.nerima.tokyo.jp/shisetsu/koen/undo/nerima.html',
  johoku: 'https://www.tokyo-park.or.jp/park/johoku-chuo/facility/',
  toda: 'https://toda-zaidan.org/sportscenter/shisetsu_sc/yoyaku_sc/#schedule',
  niiza: 'https://k5.p-kashikan.jp/niiza-city/index.php',
  komazawa: 'https://www.tef.or.jp/kopgp/opening.html',
  setagaya: 'https://www.se-sports.or.jp/news/10334/',
  oi: 'https://tokyo-south-seaside-parks.com/sports-athletics/',
  toneri: 'https://www.tokyo-park.or.jp/park/toneri/facility/index.html#park96',
  edogawa: 'https://www.edogawa-3field.jp/athletics/konzatsuguid/',
  okudo: 'https://www2.city.katsushika.lg.jp/tourism/1002753/1030217/1003242.html',
  koshigaya: 'https://kouen-kyougijyou.kosi-kanri.com/',
  kamiyugi: 'https://kamiyugi-park.jp/facility/athletics-stadium/',
  akirudai: 'https://www.tokyo-park.or.jp/park/akirudai/news/2024/park_info_1.html',
} as const;

export const expansionFallbackSources = [
  { trackId: 'koto-yumenoshima-athletic-stadium', url: 'https://yoyaku.koto-sports.net/', publicationFormat: 'reservation_system', unknownReason: 'reservation_system_unsupported' },
  { trackId: 'komazawa-olympic-park-track', url: 'https://www.tef.or.jp/kopgp/opening.html', publicationFormat: 'calendar_html', unknownReason: 'unsupported_source_type' },
  { trackId: 'setagaya-general-sports-track', url: 'https://www.se-sports.or.jp/news/10334/', publicationFormat: 'structured_html', unknownReason: 'unsupported_source_type' },
  { trackId: 'oi-central-seaside-park-track', url: 'https://tokyo-south-seaside-parks.com/sports-athletics/', publicationFormat: 'fixed_schedule', unknownReason: 'unsupported_source_type' },
  { trackId: 'toneri-park-athletic-track', url: 'https://www.tokyo-park.or.jp/park/toneri/news/', publicationFormat: 'weekly_notice', unknownReason: 'unsupported_source_type' },
  { trackId: 'edogawa-athletic-stadium', url: 'https://www.city.edogawa.tokyo.jp/e028/kuseijoho/gaiyo/shisetsuguide/bunya/sportsshisetsu/rikujokyogijo/index.html', publicationFormat: 'calendar_html', unknownReason: 'unsupported_source_type' },
  { trackId: 'okudo-sports-center-track', url: 'https://www2.city.katsushika.lg.jp/tourism/1002753/1030217/1003242.html', publicationFormat: 'fixed_schedule', unknownReason: 'unsupported_source_type' },
  { trackId: 'shingashi-athletic-track', url: 'https://www.city.itabashi.tokyo.jp/bunka/1005245/okugai/1005266.html', publicationFormat: 'reservation_system', unknownReason: 'reservation_system_unsupported' },
  { trackId: 'arakawa-todabashi-athletic-track', url: 'https://www.city.itabashi.tokyo.jp/bunka/1005245/okugai/1005266.html', publicationFormat: 'reservation_system', unknownReason: 'reservation_system_unsupported' },
  { trackId: 'fuchu-citizen-athletic-track', url: 'https://www.city.fuchu.tokyo.jp/shisetu/supotu/kyogi/shimin.html', publicationFormat: 'pdf', unknownReason: 'unsupported_source_type' },
  { trackId: 'wadabori-park-first-track', url: 'https://www.tokyo-park.or.jp/park/wadabori/news/', publicationFormat: 'pdf', unknownReason: 'unsupported_source_type' },
  { trackId: 'wadabori-park-seibiyama-track', url: 'https://www.tokyo-park.or.jp/park/wadabori/news/', publicationFormat: 'pdf', unknownReason: 'unsupported_source_type' },
  { trackId: 'kawaguchi-aoki-park-track', url: 'https://kawaspo.jp/pages/24/', publicationFormat: 'reservation_system', unknownReason: 'reservation_system_unsupported' },
  { trackId: 'misato-senario-house-field', url: 'https://www.misato-hall.com/module/3299.htm', publicationFormat: 'pdf', unknownReason: 'unsupported_source_type' },
  { trackId: 'koshigaya-shirakobato-track', url: 'https://kouen-kyougijyou.kosi-kanri.com/', publicationFormat: 'structured_html', unknownReason: 'unsupported_source_type' },
  { trackId: 'saitama-komaba-stadium-track', url: 'https://www.city.saitama.lg.jp/004/006/003/003/p033423.html', publicationFormat: 'phone_only', unknownReason: 'phone_confirmation_required' },
  { trackId: 'ageo-athletic-stadium', url: 'https://www.parks.or.jp/saitamasuijo/guide/006/006231.html', publicationFormat: 'pdf', unknownReason: 'unsupported_source_type' },
  { trackId: 'kamiyugi-park-athletic-stadium', url: 'https://kamiyugi-park.jp/facility/athletics-stadium/', publicationFormat: 'pdf', unknownReason: 'unsupported_source_type' },
  { trackId: 'hachioji-fujimori-athletic-stadium', url: 'https://www.city.hachioji.tokyo.jp/life/010/002/003/004/p012068.html', publicationFormat: 'pdf', unknownReason: 'unsupported_source_type' },
  { trackId: 'akirudai-park-athletic-track', url: 'https://www.tokyo-park.or.jp/park/akirudai/news/', publicationFormat: 'weekly_notice', unknownReason: 'unsupported_source_type' },
  { trackId: 'higashiyamato-minami-park-track', url: 'https://www.tokyo-park.or.jp/park/higashiyamato-minami/news/', publicationFormat: 'no_schedule_found', unknownReason: 'web_schedule_unavailable' },
] as const;
