import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { cacheControlForWebObject as acceptedCacheControl } from './deploy-preview.mjs'
import { WEB_DEPLOY_TARGET, cacheControlForWebObject, collectWebObjects, deployWebPreview, parseWebDeployArgs, prepareWebReportTarget, putObjectArgs, verifyWebObject, webContentType, writeWebReport } from './deploy-web-preview.mjs'

const roots = []
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })))} )
async function build() { const root = await mkdtemp(join(tmpdir(), 't15b-')); roots.push(root); await mkdir(join(root, '_nuxt')); await writeFile(join(root, 'index.html'), '<html>ok</html>'); await writeFile(join(root, '_nuxt', 'app.12345678.js'), 'alert(1)'); return root }
const config = (webDir, extra = {}) => ({ mode: 'operator', profile: 'codex-prod', webDir, ...WEB_DEPLOY_TARGET, env: {}, ...extra })
function runner(calls, identity = { Account: WEB_DEPLOY_TARGET.account }) { return async (args) => { calls.push(args); if (args[0] === 'sts') return identity; if (args[0] === 'cloudformation') return { Stacks: [{ StackStatus: 'UPDATE_COMPLETE', Outputs: [{ OutputKey: 'WebBucketName', OutputValue: WEB_DEPLOY_TARGET.bucket }, { OutputKey: 'DistributionDomainName', OutputValue: WEB_DEPLOY_TARGET.domain }] }] }; return {} } }

describe('T15B isolated web deployment', () => {
  it('builds explicit per-object commands and immutable/short/html order', () => { expect(cacheControlForWebObject('index.html')).toContain('no-cache'); expect(putObjectArgs({ key: 'index.html', path: '/tmp/index.html', contentType: 'text/html', cacheControl: cacheControlForWebObject('index.html') }, WEB_DEPLOY_TARGET.bucket)[1]).toBe('put-object') })
  it('fails identity before any write and rejects wrong mode context', async () => { const root = await build(); const calls = []; await expect(deployWebPreview(config(root), { runAws: runner(calls, { Account: 'x' }) })).rejects.toMatchObject({ category: 'identity' }); expect(calls).toHaveLength(1); await expect(deployWebPreview(config(root, { mode: 'github', profile: 'codex-prod' }), { runAws: runner([]) })).rejects.toMatchObject({ category: 'configuration' }) })
  it('accepts only the reviewed GitHub OIDC context and role after STS', async () => {
    const root = await build()
    const calls = []
    const env = { GITHUB_ACTIONS: 'true', GITHUB_REPOSITORY: 'subaru44k/itsrunnew', GITHUB_REF: 'refs/heads/migration/aws-s3-cloudfront', AWS_ACCESS_KEY_ID: 'short-lived-id', AWS_SECRET_ACCESS_KEY: 'short-lived-secret', AWS_SESSION_TOKEN: 'short-lived-session' }
    const runAws = async (args) => {
      calls.push(args)
      if (args[0] === 'sts') return { Account: WEB_DEPLOY_TARGET.account, Arn: 'arn:aws:sts::470447451992:assumed-role/itsrun-preview-github-web-deploy/session' }
      if (args[0] === 'cloudformation') return { Stacks: [{ StackStatus: 'UPDATE_COMPLETE', Outputs: [{ OutputKey: 'WebBucketName', OutputValue: WEB_DEPLOY_TARGET.bucket }, { OutputKey: 'DistributionDomainName', OutputValue: WEB_DEPLOY_TARGET.domain }] }] }
      return {}
    }
    const fetchImpl = async (url) => {
      const key = url.includes('/index.html?') ? 'index.html' : '_nuxt/app.12345678.js'
      const body = Buffer.from(key === 'index.html' ? '<html>ok</html>' : 'alert(1)')
      return new Response(body, { status: 200, headers: { 'content-type': key.endsWith('.html') ? 'text/html' : 'application/javascript', 'cache-control': cacheControlForWebObject(key) } })
    }
    await expect(deployWebPreview({ ...config(root), mode: 'github', profile: undefined, env }, { runAws, fetchImpl })).resolves.toMatchObject({ status: 'match', mode: 'github' })
    expect(calls[0]).not.toContain('--profile')
  })
  it('runs only STS, stack read, PutObject, and CloudFront verification', async () => { const root = await build(); const calls = []; const fetchImpl = async (url) => { const key = url.includes('/index.html?') ? 'index.html' : '_nuxt/app.12345678.js'; const body = Buffer.from(key === 'index.html' ? '<html>ok</html>' : 'alert(1)'); return new Response(body, { status: 200, headers: { 'content-type': key.endsWith('.html') ? 'text/html' : 'application/javascript', 'cache-control': cacheControlForWebObject(key) } }) }; const report = await deployWebPreview(config(root), { runAws: runner(calls), fetchImpl }); expect(report.status).toBe('match'); expect(calls.filter((call) => call[1] === 'put-object')).toHaveLength(2); expect(calls.flat().some((value) => /delete|sync|cp|acl|invalidation|data/i.test(value))).toBe(false) })
  it('rejects empty, hidden, symlinked, and wrong bucket builds before STS', async () => { const root = await mkdtemp(join(tmpdir(), 't15b-empty-')); roots.push(root); const calls = []; await expect(deployWebPreview(config(root), { runAws: runner(calls) })).rejects.toMatchObject({ category: 'empty' }); expect(calls).toHaveLength(0); await expect(deployWebPreview(config(root, { bucket: 'wrong' }), { runAws: runner(calls) })).rejects.toMatchObject({ category: 'configuration' }) })
  it('uses exact metadata types and cache contract for common web extensions', async () => { const root = await build(); await writeFile(join(root, 'icon.png'), 'x'); await writeFile(join(root, 'font.woff2'), 'x'); const objects = await collectWebObjects(root); expect(objects.find((object) => object.key === 'icon.png').contentType).toBe('image/png'); expect(objects.find((object) => object.key === 'font.woff2').contentType).toBe('font/woff2'); expect(objects.every((object) => object.cacheControl === cacheControlForWebObject(object.key))).toBe(true) })
  it('covers every deterministic MIME branch and accepted cache classifier', async () => { const root = await build(); for (const extension of ['jpg', 'jpeg', 'gif', 'webp', 'ico', 'woff', 'txt', 'xml', 'webmanifest', 'map', 'bin']) await writeFile(join(root, `asset.${extension}`), 'x'); const objects = await collectWebObjects(root); const types = Object.fromEntries(objects.map((object) => [object.key, object.contentType])); expect(types['asset.jpg']).toBe('image/jpeg'); expect(types['asset.jpeg']).toBe('image/jpeg'); expect(types['asset.gif']).toBe('image/gif'); expect(types['asset.webp']).toBe('image/webp'); expect(types['asset.ico']).toBe('image/x-icon'); expect(types['asset.woff']).toBe('font/woff'); expect(types['asset.txt']).toBe('text/plain'); expect(types['asset.xml']).toBe('application/xml'); expect(types['asset.webmanifest']).toBe('application/manifest+json'); expect(types['asset.map']).toBe('application/json'); expect(types['asset.bin']).toBe('application/octet-stream'); for (const key of ['index.html', '_nuxt/app.12345678.js', 'asset.bin']) expect(cacheControlForWebObject(key)).toBe(acceptedCacheControl(key)) })
  it.each([['html', 'text/html'], ['json', 'application/json'], ['js', 'application/javascript'], ['css', 'text/css'], ['svg', 'image/svg+xml'], ['png', 'image/png'], ['jpg', 'image/jpeg'], ['jpeg', 'image/jpeg'], ['gif', 'image/gif'], ['webp', 'image/webp'], ['ico', 'image/x-icon'], ['woff', 'font/woff'], ['woff2', 'font/woff2'], ['txt', 'text/plain'], ['xml', 'application/xml'], ['webmanifest', 'application/manifest+json'], ['map', 'application/json'], ['unknown', 'application/octet-stream']])('maps .%s to exact MIME', (extension, expected) => { expect(webContentType(`asset.${extension}`)).toBe(expected) })
  it('bounds hanging fetch and encodes key segments with hash query', async () => { const object = { key: '_nuxt/a b.js', sha256: 'a'.repeat(64), contentType: 'application/javascript', cacheControl: 'public, max-age=86400' }; let seen; await expect(verifyWebObject(WEB_DEPLOY_TARGET.domain, object, { timeoutMs: 20, maxAttempts: 1, fetchImpl: (url, options) => { seen = [url, options.signal]; return new Promise(() => {}) } })).rejects.toMatchObject({ category: 'timeout' }); expect(seen[0]).toContain('_nuxt/a%20b.js?sha256='); expect(seen[1].aborted).toBe(true) })
  it('bounds hanging body, hanging retry sleep, and clears success timers', async () => { const body = Buffer.from('x'); const object = { key: 'index.html', sha256: createHash('sha256').update(body).digest('hex'), contentType: 'text/html', cacheControl: 'no-cache, no-store, must-revalidate' }; await expect(verifyWebObject(WEB_DEPLOY_TARGET.domain, object, { timeoutMs: 20, maxAttempts: 1, fetchImpl: async () => ({ status: 200, headers: new Headers({ 'content-type': 'text/html', 'cache-control': object.cacheControl }), arrayBuffer: () => new Promise(() => {}) }) })).rejects.toMatchObject({ category: 'timeout' }); let attempts = 0; await expect(verifyWebObject(WEB_DEPLOY_TARGET.domain, object, { timeoutMs: 20, maxAttempts: 3, fetchImpl: async () => { attempts += 1; throw new Error('retry') }, sleep: () => new Promise(() => {}) })).rejects.toMatchObject({ category: 'timeout' }); expect(attempts).toBe(1); vi.useFakeTimers(); try { await verifyWebObject(WEB_DEPLOY_TARGET.domain, object, { timeoutMs: 100, maxAttempts: 1, fetchImpl: async () => new Response(body, { status: 200, headers: { 'content-type': 'text/html', 'cache-control': object.cacheControl } }) }); expect(vi.getTimerCount()).toBe(0) } finally { vi.useRealTimers() } })
  it('rejects malformed argument modes and forged report handles', async () => { expect(() => parseWebDeployArgs(['--mode', 'operator', '--web-dir', '/x', '--report-dir', '/x', '--unknown', 'x'])).toThrow(); await expect(writeWebReport({ root: '/tmp', target: '/tmp/report' }, { status: 'match' })).rejects.toMatchObject({ category: 'report' }); await expect(prepareWebReportTarget('/tmp', '/tmp/.artifacts/migration/run-test')).rejects.toMatchObject({ category: 'report' }) })
  it('rejects real root/nested symlinks, hidden files, and oversized files', async () => { const outside = await mkdtemp(join(tmpdir(), 't15br3-out-')); const root = await mkdtemp(join(tmpdir(), 't15br3-root-')); roots.push(outside, root); await writeFile(join(outside, 'secret.txt'), 'x'); await mkdir(join(root, 'nested')); await (await import('node:fs/promises')).symlink(join(outside, 'secret.txt'), join(root, 'linked.txt')); await expect(collectWebObjects(root)).rejects.toMatchObject({ category: 'path' }); await rm(join(root, 'linked.txt')); await writeFile(join(root, 'nested', '.hidden'), 'x'); await expect(collectWebObjects(root)).rejects.toMatchObject({ category: 'path' }); await rm(join(root, 'nested', '.hidden')); await writeFile(join(root, 'huge.bin'), Buffer.alloc(10 * 1024 * 1024 + 1)); await expect(collectWebObjects(root)).rejects.toMatchObject({ category: 'path' }); const rootLink = join(tmpdir(), `t15br3-link-${Date.now()}`); await (await import('node:fs/promises')).symlink(root, rootLink); await expect(collectWebObjects(rootLink)).rejects.toMatchObject({ category: 'path' }); await rm(rootLink, { force: true }) })
  it('uses injected directory enumeration and rejects special/stat mismatch before AWS', async () => { const root = await build(); const calls = []; const fsApi = { readdir: async () => [{ name: 'fifo', isDirectory: () => false, isFile: () => false, isSymbolicLink: () => false }], lstat: async () => ({ isDirectory: () => true, isFile: () => false, isSymbolicLink: () => false }), readFile: async () => Buffer.from('x') }; await expect(deployWebPreview(config(root), { fsApi, runAws: async (args) => { calls.push(args); return {} } })).rejects.toMatchObject({ category: 'path' }); expect(calls).toHaveLength(0); const mismatch = { readdir: async () => [{ name: 'index.html', isDirectory: () => false, isFile: () => true, isSymbolicLink: () => false }], lstat: async (path) => path.endsWith('index.html') ? ({ isDirectory: () => false, isFile: () => true, isSymbolicLink: () => false, size: 2 }) : ({ isDirectory: () => true, isFile: () => false, isSymbolicLink: () => false }), readFile: async () => Buffer.from('x') }; await expect(deployWebPreview(config(root), { fsApi: mismatch, runAws: async (args) => { calls.push(args); return {} } })).rejects.toMatchObject({ category: 'size' }); expect(calls).toHaveLength(0) })
  it('rejects near-match assumed roles, duplicate outputs, and non-terminal stacks before puts', async () => { const root = await build(); const calls = []; const env = { GITHUB_ACTIONS: 'true', GITHUB_REPOSITORY: 'subaru44k/itsrunnew', GITHUB_REF: 'refs/heads/migration/aws-s3-cloudfront', AWS_ACCESS_KEY_ID: 'id', AWS_SECRET_ACCESS_KEY: 'secret', AWS_SESSION_TOKEN: 'session' }; const near = runner(calls, { Account: WEB_DEPLOY_TARGET.account, Arn: 'arn:aws:sts::470447451992:assumed-role/itsrun-preview-github-web-deploy/session/extra' }); await expect(deployWebPreview({ ...config(root), mode: 'github', profile: undefined, env }, { runAws: near })).rejects.toMatchObject({ category: 'identity' }); expect(calls).toHaveLength(1); const badStack = async (args) => { calls.push(args); if (args[0] === 'sts') return { Account: WEB_DEPLOY_TARGET.account }; return { Stacks: [{ StackStatus: 'CREATE_COMPLETE', Outputs: [] }, { StackStatus: 'UPDATE_COMPLETE', Outputs: [] }] } }; await expect(deployWebPreview(config(root), { runAws: badStack })).rejects.toMatchObject({ category: 'stack' }); expect(calls.filter((call) => call[1] === 'put-object')).toHaveLength(0) })
  it.each(['missing-id', 'missing-secret', 'missing-session', 'whitespace-id', 'whitespace-secret', 'whitespace-session'])('rejects GitHub credential case %s before STS', async (caseName) => { const root = await build(); const env = { GITHUB_ACTIONS: 'true', GITHUB_REPOSITORY: 'subaru44k/itsrunnew', GITHUB_REF: 'refs/heads/migration/aws-s3-cloudfront', AWS_ACCESS_KEY_ID: 'id', AWS_SECRET_ACCESS_KEY: 'secret', AWS_SESSION_TOKEN: 'session' }; if (caseName === 'missing-id') delete env.AWS_ACCESS_KEY_ID; if (caseName === 'missing-secret') delete env.AWS_SECRET_ACCESS_KEY; if (caseName === 'missing-session') delete env.AWS_SESSION_TOKEN; if (caseName === 'whitespace-id') env.AWS_ACCESS_KEY_ID = '   '; if (caseName === 'whitespace-secret') env.AWS_SECRET_ACCESS_KEY = '   '; if (caseName === 'whitespace-session') env.AWS_SESSION_TOKEN = '   '; const calls = []; await expect(deployWebPreview({ ...config(root), mode: 'github', profile: undefined, env }, { runAws: async (args) => { calls.push(args); return {} } })).rejects.toMatchObject({ category: 'configuration' }); expect(calls).toHaveLength(0) })
  it.each(['status', 'mime', 'cache', 'hash'])('sanitizes CloudFront %s failure', async (kind) => { const body = Buffer.from('x'); const object = { key: 'index.html', sha256: createHash('sha256').update(body).digest('hex'), contentType: 'text/html', cacheControl: 'no-cache, no-store, must-revalidate' }; const response = kind === 'status' ? new Response(body, { status: 503, headers: {} }) : kind === 'mime' ? new Response(body, { status: 200, headers: { 'content-type': 'text/plain', 'cache-control': object.cacheControl } }) : kind === 'cache' ? new Response(body, { status: 200, headers: { 'content-type': 'text/html', 'cache-control': 'public, max-age=60' } }) : new Response('wrong', { status: 200, headers: { 'content-type': 'text/html', 'cache-control': object.cacheControl } }); await expect(verifyWebObject(WEB_DEPLOY_TARGET.domain, object, { maxAttempts: 1, timeoutMs: 100, fetchImpl: async () => response })).rejects.toMatchObject({ category: 'cloudfront' }) })
  it.each(['zero', 'two', 'status', 'missing', 'duplicate'])('rejects stack shape %s without PutObject', async (shape) => { const root = await build(); const calls = []; const stack = shape === 'zero' ? [] : shape === 'two' ? [{ StackStatus: 'UPDATE_COMPLETE', Outputs: [] }, { StackStatus: 'UPDATE_COMPLETE', Outputs: [] }] : shape === 'status' ? [{ StackStatus: 'CREATE_COMPLETE', Outputs: [] }] : [{ StackStatus: 'UPDATE_COMPLETE', Outputs: shape === 'missing' ? [] : [{ OutputKey: 'WebBucketName', OutputValue: WEB_DEPLOY_TARGET.bucket }, { OutputKey: 'WebBucketName', OutputValue: WEB_DEPLOY_TARGET.bucket }] }]; const runAws = async (args) => { calls.push(args); if (args[0] === 'sts') return { Account: WEB_DEPLOY_TARGET.account }; return { Stacks: stack } }; await expect(deployWebPreview(config(root), { runAws })).rejects.toMatchObject({ category: 'stack' }); expect(calls.filter((call) => call[1] === 'put-object')).toHaveLength(0) })
})
