import { mkdir, readFile, rm } from 'node:fs/promises'
import { mkdtemp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { buildReadPlan, readFirestoreSnapshot, runCli, serializeExport, validateExportConfig, writeExportRun, ExportValidationError } from './export-firestore.mjs'
import { normalizeFirestoreSnapshot } from '../../packages/core/src/firestoreSnapshot.ts'
const fixture = JSON.parse(await readFile(new URL('./fixtures/firestore-snapshot.synthetic.json', import.meta.url), 'utf8'))
const config = { projectId: 'itsrun-aaf42', databaseId: '(default)', capturedAt: '2026-08-09T00:00:00.000Z' }
function fakeAdapter(order = []) { return { async getDocument(path) { order.push(`doc:${path}`); return { exists: false, data: null } }, async getCollection(path) { order.push(`collection:${path}`); if (path === 'stadium_info') return { docs: [{ id: 'z', data: { name: 'Z' } }, { id: 'a', data: { name: 'A' } }] }; const item = fixture.collections.find((value) => path === `availability/${value.legacyId}/date`); return { docs: item.documents.map((doc) => ({ id: doc.path.split('/').at(-1), data: doc.data })) } } } }
describe('T14E1R01 exporter artifact contract', () => {
  it('reads the exact allowlist and emits T14A-consumable snapshot', async () => { const order = []; const result = await readFirestoreSnapshot(fakeAdapter(order), config); expect(order).toEqual(['doc:default/0', 'collection:stadium_info', ...Object.values({ oda: 'nVfuSmsj9cULg3712chv', yumenoshima: 'VFurPbbeejEbtu1JNTzF', komazawa: 'WrrQXe67xvIkGfMtJ51E', todoroki: '67c7uxgRWDkxr1S4gPaR' }).map((id) => `collection:availability/${id}/date`)]); expect(result.snapshot).toEqual(expect.objectContaining({ schemaVersion: 1, collections: expect.any(Array) })); expect(normalizeFirestoreSnapshot(result.snapshot)).toHaveLength(4); expect(JSON.parse(new TextDecoder().decode(result.snapshotBytes))).toEqual(result.snapshot) })
  it('keeps snapshot bytes/hash stable while capture metadata changes', async () => { const a = await readFirestoreSnapshot(fakeAdapter(), config); const b = await readFirestoreSnapshot(fakeAdapter(), { ...config, capturedAt: '2026-08-09T00:01:00.000Z' }); expect([...a.snapshotBytes]).toEqual([...b.snapshotBytes]); expect(a.normalizedDataSha256).toBe(b.normalizedDataSha256); expect([...a.captureBytes]).not.toEqual([...b.captureBytes]) })
  it('handles empty collections and rejects malformed/bounded/unsafe adapters', async () => { const empty = await readFirestoreSnapshot({ getDocument: async () => ({ exists: false, data: null }), getCollection: async () => ({ docs: [] }) }, config); expect(normalizeFirestoreSnapshot(empty.snapshot)).toEqual([]); await expect(readFirestoreSnapshot({ getDocument: async () => ({ exists: false }), getCollection: async () => ({ docs: Array.from({ length: 10001 }, (_, i) => ({ id: `${i}`, data: {} })) }) }, config)).rejects.toBeInstanceOf(ExportValidationError); await expect(readFirestoreSnapshot({ getDocument: async () => ({ exists: false }), getCollection: async () => { throw new Error('raw sdk secret') } }, config)).rejects.toMatchObject({ category: 'adapter' }); await expect(readFirestoreSnapshot({ getDocument: async () => ({ exists: false }), getCollection: async () => ({ docs: [] }), delete: async () => {} }, config)).rejects.toMatchObject({ category: 'adapter' }) })
  it('rejects config credentials/emulator and duplicate IDs', async () => { for (const invalid of [{ ...config, projectId: 'other' }, { ...config, databaseId: 'db2' }, { ...config, env: { GOOGLE_APPLICATION_CREDENTIALS: '/secret' } }, { ...config, env: { FIRESTORE_EMULATOR_HOST: 'localhost:8080' } }]) expect(() => validateExportConfig(invalid)).toThrow(ExportValidationError); const duplicate = { getDocument: async () => ({ exists: false }), getCollection: async (path) => path === 'stadium_info' ? { docs: [{ id: 'a', data: {} }, { id: 'a', data: {} }] } : { docs: [] } }; await expect(readFirestoreSnapshot(duplicate, config)).rejects.toBeInstanceOf(ExportValidationError) })
  it('writes an exact two-file atomic run, rereads it, and refuses reuse', async () => { const root = await mkdtemp(join(tmpdir(), 't14e-root-')); await mkdir(join(root, 'migration')); const result = await readFirestoreSnapshot(fakeAdapter(), config); const run = await writeExportRun(result, 'run-1', { artifactRoot: join(root, 'migration') }); expect(await readFile(join(run, 'snapshot.json'))).toEqual(Buffer.from(result.snapshotBytes)); expect(await readFile(join(run, 'capture.json'))).toEqual(Buffer.from(result.captureBytes)); await expect(writeExportRun(result, 'run-1', { artifactRoot: join(root, 'migration') })).rejects.toBeInstanceOf(ExportValidationError); await rm(root, { recursive: true, force: true }) })
  it('help/invalid invocation are offline and lifecycle seam closes the app', async () => { expect(await runCli(['--help'], {})).toBe(0); expect(await runCli([], {})).toBe(2); let initialized = 0; let deleted = 0; const loader = async () => ({ applicationDefault: () => ({}), initializeApp: () => { initialized += 1; return {} }, getFirestore: () => ({ doc: () => ({ get: async () => ({ exists: false }) }), collection: () => ({ get: async () => ({ docs: [] }) }) }), deleteApp: async () => { deleted += 1 } }); await expect(runCli(['--output', '../bad'], {}, loader)).rejects.toBeInstanceOf(ExportValidationError); expect(initialized).toBe(0); expect(deleted).toBe(0) })
})
