import { lstat, mkdtemp, mkdir, readFile, readdir, realpath, rm, symlink, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { normalizeFirestoreSnapshot } from '../../packages/core/src/firestoreSnapshot.ts'
import { main as uploadCliMain, parseUploadCliArgs } from './firestore-upload-cli.mjs'
import { transformFirestoreRecords } from './firestore-transform.mjs'
import { getObjectVersionArgs, headObjectArgs, humanUploadReport, preflightAwsExecutable, preflightSealedAbsence, putObjectArgs, readBoundedFile, restoreObjectArgs, runAwsJson, sealUploadRun, serializeUploadReport, stsArgs, uploadMigrationRun, uploadSealedMigrationRun, writeUploadReports } from './firestore-upload.mjs'

const raw = JSON.parse(await readFile(new URL('./fixtures/firestore-snapshot.synthetic.json', import.meta.url), 'utf8'))
const records = normalizeFirestoreSnapshot(raw)
const options = { sourceIdentity: 'synthetic-fixture', updatedAt: '2026-08-09T00:00:00.000Z' }
const result = transformFirestoreRecords(records, options)
const bucket = 'itsrun-preview-data-470447451992-ap-northeast-1'
const approvedTarget = { bucket, distributionDomain: 'preview.example.test' }
const baseConfig = { profile: 'codex-prod', account: '470447451992', region: 'ap-northeast-1', bucket, distributionDomain: 'preview.example.test', maxAttempts: 2, timeoutMs: 100 }
const body = (object) => new TextDecoder().decode(object.body)

async function createRun() {
  const runDir = await mkdtemp(join(tmpdir(), 't14d-')); await mkdir(join(runDir, 'data/v1/stadiums'), { recursive: true })
  for (const object of result.objects) { const path = join(runDir, object.key); await mkdir(join(path, '..'), { recursive: true }); await writeFile(path, object.body) }
  const manifestPath = join(runDir, 'manifest.json'); await writeFile(manifestPath, result.manifestBytes); return { runDir, manifestPath, config: { ...baseConfig, runDir, manifestPath, readbackRoot: runDir, restoreRoot: runDir } }
}

function successFetch() { return async (url) => { const object = result.objects.find((candidate) => url.endsWith(candidate.key)); return new Response(body(object), { status: 200, headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60', age: '0' } }) } }

describe('T14D injected local upload tooling', () => {
  it('builds exact AWS arguments and never includes forbidden operations', () => {
    const config = { ...baseConfig, runDir: '/safe/run', readbackRoot: '/safe/run/read', restoreRoot: '/safe/restore' }; const object = { ...result.objects[0], bodyPath: '/safe/run/data.json', versionId: 'v1', etag: '"abc123"' }
    expect(stsArgs(config)).toEqual(['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 'sts', 'get-caller-identity'])
    expect(putObjectArgs(config, object)).toEqual(['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 's3api', 'put-object', '--bucket', bucket, '--key', object.key, '--body', object.bodyPath, '--content-type', 'application/json', '--cache-control', 'public, max-age=0, s-maxage=60', '--if-none-match', '*'])
    expect(getObjectVersionArgs(config, object, '/safe/run/read/read.json')).toEqual(['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 's3api', 'get-object', '--bucket', bucket, '--key', object.key, '--version-id', 'v1', '/safe/run/read/read.json'])
    expect(restoreObjectArgs(config, object, '/safe/restore/old.json')).toEqual(['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 's3api', 'put-object', '--bucket', bucket, '--key', object.key, '--body', '/safe/restore/old.json', '--content-type', 'application/json', '--cache-control', 'public, max-age=0, s-maxage=60', '--if-match', '"abc123"'])
    const text = JSON.stringify([stsArgs(config), putObjectArgs(config, object), getObjectVersionArgs(config, object, '/safe/run/read/read.json'), restoreObjectArgs(config, object, '/safe/restore/old.json')]); expect(text).not.toMatch(/delete|sync|cp|invalidation|s3:\*/i)
    expect(() => stsArgs({ ...config, distributionDomain: 'https://preview.example.test/path' })).toThrow()
    expect(() => putObjectArgs(config, { ...object, bodyPath: '/safe/run/../secret.json' })).toThrow()
    expect(() => getObjectVersionArgs(config, object, '/safe/run/read/../../secret.json')).toThrow()
    expect(() => restoreObjectArgs(config, object, '/safe/restore/-secret.json')).toThrow()
  })

  it('requires a separate approved target and validates target DNS syntax before any injected call', async () => {
    const { runDir, config } = await createRun(); const calls = []; const runAws = async () => { calls.push('aws'); return { Account: '470447451992' } }
    const missing = await uploadMigrationRun(config, { runAws, fetch: successFetch() }); expect(missing.report.failure.stage).toBe('preflight'); expect(calls).toEqual([])
    const selfApproval = await uploadMigrationRun({ ...config, approvedTarget: { bucket: config.bucket, distributionDomain: config.distributionDomain } }, { runAws, fetch: successFetch() }); expect(selfApproval.report.failure.stage).toBe('preflight'); expect(calls).toEqual([])
    for (const domain of ['preview.example.test:443', 'https://preview.example.test', 'a..b.test', '*.example.test', '127.0.0.1']) { const invalid = await uploadMigrationRun({ ...config, distributionDomain: domain }, { runAws, fetch: successFetch(), approvedTarget: { bucket: config.bucket, distributionDomain: domain } }); expect(invalid.report.failure.stage).toBe('preflight'); expect(calls).toEqual([]) }
    const mismatch = await uploadMigrationRun(config, { runAws, fetch: successFetch(), approvedTarget: { bucket: 'other-bucket', distributionDomain: config.distributionDomain } }); expect(mismatch.report.failure.stage).toBe('preflight'); expect(calls).toEqual([]); await rm(runDir, { recursive: true, force: true })
  })

  it('always performs STS through the public upload API even when skipSts is supplied', async () => {
    const { runDir, config } = await createRun(); const calls = []; const runAws = async (args) => { calls.push(args); if (args.includes('get-caller-identity')) return { Account: '470447451992' }; throw Object.assign(new Error(), { code: 412 }) }
    const resultWithIgnoredOption = await uploadMigrationRun(config, { runAws, fetch: successFetch(), approvedTarget, skipSts: true }); expect(resultWithIgnoredOption.report.failure.stage).toBe('upload'); expect(calls.filter((args) => args.includes('get-caller-identity'))).toHaveLength(1); await rm(runDir, { recursive: true, force: true })
  })

  it('reads only maxBytes plus one and always closes the injected handle', async () => {
    const reads = []; let closed = 0
    const fs = { open: async () => ({ read: async (buffer, offset, length) => { reads.push(length); buffer.fill(65, offset, offset + length); return { bytesRead: length } }, close: async () => { closed += 1 } }) }
    await expect(readBoundedFile(fs, '/manifest.json', 10)).rejects.toThrow(); expect(reads).toEqual([11]); expect(closed).toBe(1)
    let done = false; closed = 0
    const exactFs = { open: async () => ({ read: async (buffer, offset, length) => { if (done) return { bytesRead: 0 }; done = true; buffer.fill(65, offset, offset + length); return { bytesRead: length - 1 } }, close: async () => { closed += 1 } }) }
    await expect(readBoundedFile(exactFs, '/manifest.json', 10)).resolves.toHaveLength(10); expect(closed).toBe(1)
    const closeFailFs = { open: async () => ({ read: async () => ({ bytesRead: 0 }), close: async () => { throw new Error('raw close path') } }) }; await expect(readBoundedFile(closeFailFs, '/manifest.json', 10)).rejects.toThrow('raw close path')
    let closeCount = 0; const readCloseFailFs = { open: async () => ({ read: async () => { throw new Error('raw read path') }, close: async () => { closeCount += 1; throw new Error('raw close path') } }) }; await expect(readBoundedFile(readCloseFailFs, '/manifest.json', 10)).rejects.toThrow('raw close path'); expect(closeCount).toBe(1)
  })

  it('rejects recursive depth and global file-count overflow before AWS', async () => {
    const { runDir: depthDir, config: depthConfig } = await createRun(); let nested = depthDir; for (let index = 0; index < 18; index += 1) { nested = join(nested, `d${index}`); await mkdir(nested) }; await writeFile(join(nested, 'extra.txt'), 'x'); const calls = []; const depth = await uploadMigrationRun(depthConfig, { runAws: async () => { calls.push('aws') }, fetch: successFetch(), approvedTarget }); expect(depth.report.failure.stage).toBe('preflight'); expect(calls).toEqual([]); await rm(depthDir, { recursive: true, force: true })
    const { runDir: countDir, config: countConfig } = await createRun(); await writeFile(join(countDir, 'extra-a.txt'), 'x'); const count = await uploadMigrationRun(countConfig, { runAws: async () => { calls.push('aws') }, fetch: successFetch(), approvedTarget }); expect(count.report.failure.stage).toBe('preflight'); expect(calls).toEqual([]); await rm(countDir, { recursive: true, force: true })
  })

  it('accepts only the explicit upload report state-machine matrix', () => {
    const tagged = result.objects.slice(0, 2).map((object) => ({ key: object.key, sha256: object.sha256, etag: '"abc123"', versionId: 'v1' })); const nullTagged = tagged.map((object) => ({ ...object, etag: null, versionId: null })); const valid = [
      { schemaVersion: 1, status: 'mismatch', counts: { attempted: 0, uploaded: 0, readback: 0, cloudfront: 0 }, objects: [], failure: { stage: 'preflight', category: 'config', key: null } },
      { schemaVersion: 1, status: 'mismatch', counts: { attempted: 0, uploaded: 0, readback: 0, cloudfront: 0 }, objects: [], failure: { stage: 'sts', category: 'sts', key: null } },
      { schemaVersion: 1, status: 'mismatch', counts: { attempted: 2, uploaded: 1, readback: 0, cloudfront: 0 }, objects: [tagged[0], nullTagged[1]], failure: { stage: 'upload', category: 'collision', key: tagged[1].key } },
      { schemaVersion: 1, status: 'mismatch', counts: { attempted: 2, uploaded: 2, readback: 1, cloudfront: 0 }, objects: tagged, failure: { stage: 'readback', category: 'readback', key: tagged[1].key } },
      { schemaVersion: 1, status: 'mismatch', counts: { attempted: 2, uploaded: 2, readback: 2, cloudfront: 0 }, objects: tagged, failure: { stage: 'cleanup', category: 'readback', key: null } },
      { schemaVersion: 1, status: 'mismatch', counts: { attempted: 2, uploaded: 2, readback: 2, cloudfront: 1 }, objects: tagged, failure: { stage: 'cloudfront', category: 'timeout', key: tagged[1].key } },
      { schemaVersion: 1, status: 'match', counts: { attempted: 2, uploaded: 2, readback: 2, cloudfront: 2 }, objects: tagged, failure: null }
    ]; for (const report of valid) expect(() => serializeUploadReport(report)).not.toThrow()
    const invalid = [
      { ...valid[0], failure: { stage: 'preflight', category: 'collision', key: null } },
      { ...valid[1], counts: { attempted: 1, uploaded: 0, readback: 0, cloudfront: 0 } },
      { ...valid[2], objects: [tagged[0], tagged[1]] },
      { ...valid[2], counts: { attempted: 2, uploaded: 0, readback: 0, cloudfront: 0 } },
      { ...valid[3], failure: { stage: 'readback', category: 'readback', key: tagged[0].key } },
      { ...valid[4], counts: { attempted: 2, uploaded: 2, readback: 1, cloudfront: 0 } },
      { ...valid[5], failure: { stage: 'cloudfront', category: 'config', key: tagged[1].key } },
      { ...valid[5], objects: [{ ...tagged[0], etag: null }, tagged[1]] },
      { ...valid[6], failure: { stage: 'cloudfront', category: 'cloudfront', key: tagged[1].key } }
    ]; for (const report of invalid) expect(() => serializeUploadReport(report)).toThrow()
  })

  it('preflights local artifacts, uploads/readbacks deterministically, then verifies CloudFront', async () => {
    const { runDir, manifestPath, config } = await createRun(); const calls = []; const runAws = async (args) => { calls.push(args); if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: `v${calls.length}` }; const output = args.at(-1); const key = args[args.indexOf('--key') + 1]; await writeFile(output, result.objects.find((object) => object.key === key).body); return {} }
    const uploaded = await uploadMigrationRun(config, { runAws, fetch: successFetch(), approvedTarget }); expect(uploaded.report).toMatchObject({ status: 'match', counts: { attempted: 4, uploaded: 4, readback: 4, cloudfront: 4 } }); expect(calls.filter((args) => args.includes('put-object'))).toHaveLength(4); expect(calls.filter((args) => args.includes('get-object'))).toHaveLength(4); expect(uploaded.human).toContain('Failure: none'); expect([...await readFile(manifestPath)]).toEqual([...result.manifestBytes]); await rm(runDir, { recursive: true, force: true })
  })

  it('does not call AWS for config, path, extra-file, symlink, or STS mismatch', async () => {
    const { runDir, config } = await createRun(); const calls = []; const fake = async () => { calls.push('called'); return { Account: 'wrong' } }
    const invalidConfig = await uploadMigrationRun({ ...config, bucket: 'other' }, { runAws: fake, fetch: successFetch(), approvedTarget }); expect(invalidConfig.report.failure.category).toBe('config'); expect(invalidConfig.report.failure.stage).toBe('preflight'); expect(calls).toEqual([])
    await writeFile(join(runDir, 'extra.txt'), 'x'); const extra = await uploadMigrationRun(config, { runAws: fake, fetch: successFetch(), approvedTarget }); expect(extra.report.failure.category).toBe('preflight'); expect(calls).toEqual([]); await rm(join(runDir, 'extra.txt'))
    const outside = await mkdtemp(join(tmpdir(), 't14d-out-')); const expected = join(runDir, result.objects[0].key); await rm(expected); await symlink(join(outside, 'body'), expected); await writeFile(join(outside, 'body'), result.objects[0].body); const link = await uploadMigrationRun(config, { runAws: fake, fetch: successFetch(), approvedTarget }); expect(link.report.failure.category).toBe('preflight'); expect(calls).toEqual([]); await rm(outside, { recursive: true, force: true }); await rm(runDir, { recursive: true, force: true })
    const { runDir: stsDir, config: stsConfig } = await createRun(); const sts = await uploadMigrationRun(stsConfig, { runAws: fake, fetch: successFetch(), approvedTarget }); expect(sts.report.failure.stage).toBe('sts'); expect(calls).toContain('called'); await rm(stsDir, { recursive: true, force: true })
    const { runDir: openDir, config: openConfig } = await createRun(); const opened = await uploadMigrationRun(openConfig, { runAws: fake, fetch: successFetch(), approvedTarget, fsImpl: { open: async () => { throw new Error('raw file path') } } }); expect(opened.report.failure).toEqual({ stage: 'preflight', category: 'preflight', key: null }); expect(JSON.stringify(opened.report)).not.toContain('raw file path'); await rm(openDir, { recursive: true, force: true })
    const { runDir: ioDir, config: ioConfig } = await createRun(); let ioClosed = 0; const io = await uploadMigrationRun(ioConfig, { runAws: fake, fetch: successFetch(), approvedTarget, fsImpl: { open: async () => ({ read: async () => { throw new Error('raw read path') }, close: async () => { ioClosed += 1; throw new Error('raw close path') } }) } }); expect(io.report.failure).toEqual({ stage: 'preflight', category: 'preflight', key: null }); expect(JSON.stringify(io.report)).not.toMatch(/raw (read|close) path/); expect(ioClosed).toBe(1); await rm(ioDir, { recursive: true, force: true })
  })

  it('stops on conditional collision without later writes or retries', async () => {
    const { runDir, config } = await createRun(); const calls = []; const runAws = async (args) => { calls.push(args); if (args.includes('get-caller-identity')) return { Account: '470447451992' }; throw Object.assign(new Error('raw secret'), { code: 412 }) }; const report = await uploadMigrationRun(config, { runAws, fetch: successFetch(), approvedTarget }); expect(report.report.failure.category).toBe('collision'); expect(report.report.counts).toMatchObject({ attempted: 1, uploaded: 0 }); expect(calls.filter((args) => args.includes('put-object'))).toHaveLength(1); expect(JSON.stringify(report.report)).not.toMatch(/raw secret|bucket|domain/i); await rm(runDir, { recursive: true, force: true })
  })

  it('reports readback and CloudFront failures safely and validates report schema', async () => {
    const { runDir, config } = await createRun(); const runAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), 'bad'); return {} }; const readback = await uploadMigrationRun(config, { runAws, fetch: successFetch(), approvedTarget }); expect(readback.report.failure.stage).toBe('readback'); expect(readback.report.counts.uploaded).toBe(4); await rm(runDir, { recursive: true, force: true })
    const success = { schemaVersion: 1, status: 'match', counts: { attempted: 0, uploaded: 0, readback: 0, cloudfront: 0 }, objects: [], failure: null }; expect(serializeUploadReport(success)).toBeInstanceOf(Uint8Array); expect(humanUploadReport(success)).toContain('Failure: none')
  })

  it('reports the second object as the current failure and rejects tag omissions without later calls', async () => {
    const { runDir: readDir, config: readConfig } = await createRun(); let readCount = 0; const readAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; readCount += 1; const key = args[args.indexOf('--key') + 1]; await writeFile(args.at(-1), result.objects.find((object) => object.key === key).body); if (readCount === 2) throw Object.assign(new Error(), { code: 'hash' }) }
    const readback = await uploadMigrationRun(readConfig, { runAws: readAws, fetch: successFetch(), approvedTarget }); expect(readback.report.failure.stage).toBe('readback'); expect(readback.report.failure.key).toBe(readback.report.objects[1].key); expect(readback.report.counts.uploaded).toBe(4); await rm(readDir, { recursive: true, force: true })
    const { runDir: tagDir, config: tagConfig } = await createRun(); let putCount = 0; const tagAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) { putCount += 1; return { ETag: null, VersionId: 'v1' } } throw new Error('must not read back') }
    const tags = await uploadMigrationRun(tagConfig, { runAws: tagAws, fetch: successFetch(), approvedTarget }); expect(tags.report.failure.stage).toBe('upload'); expect(tags.report.failure.key).toBe(result.objects[0].key); expect(tags.report.counts).toMatchObject({ attempted: 1, uploaded: 0 }); expect(putCount).toBe(1); await rm(tagDir, { recursive: true, force: true })
    const { runDir: versionDir, config: versionConfig } = await createRun(); let versionPutCount = 0; const versionAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) { versionPutCount += 1; return { ETag: '"abc123"', VersionId: 'bad value' } } throw new Error('must not read back') }
    const versions = await uploadMigrationRun(versionConfig, { runAws: versionAws, fetch: successFetch(), approvedTarget }); expect(versions.report.failure.stage).toBe('upload'); expect(versions.report.failure.key).toBe(result.objects[0].key); expect(versions.report.counts.uploaded).toBe(0); expect(versionPutCount).toBe(1); await rm(versionDir, { recursive: true, force: true })
    const { runDir: edgeDir, config: edgeConfig } = await createRun(); const edgeAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; const key = args[args.indexOf('--key') + 1]; await writeFile(args.at(-1), result.objects.find((object) => object.key === key).body); return {} }; const edgeFetch = async (url) => { if (url.endsWith(result.objects[1].key)) return new Response('', { status: 503 }); return new Response(body(result.objects.find((object) => url.endsWith(object.key))), { status: 200, headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60' } }) }
    const edge = await uploadMigrationRun(edgeConfig, { runAws: edgeAws, fetch: edgeFetch, approvedTarget }); expect(edge.report.failure.stage).toBe('cloudfront'); expect(edge.report.failure.key).toBe(result.objects[1].key); expect(edge.report.counts.cloudfront).toBe(1); await rm(edgeDir, { recursive: true, force: true })
    const tampered = { schemaVersion: 1, status: 'mismatch', counts: { attempted: 1, uploaded: 1, readback: 0, cloudfront: 0 }, objects: [{ key: result.objects[0].key, sha256: result.objects[0].sha256, etag: null, versionId: null }], failure: { stage: 'readback', category: 'readback', key: null, raw: 'secret/path' } }; expect(() => serializeUploadReport(tampered)).toThrow(); expect(() => humanUploadReport(tampered)).toThrow()
    const illegalStage = { ...tampered, failure: { stage: 'cleanup', category: 'readback', key: result.objects[0].key } }; expect(() => serializeUploadReport(illegalStage)).toThrow()
    const wrongKey = { ...tampered, failure: { stage: 'readback', category: 'readback', key: 'data/v1/stadiums/oda/availability/2024-02.json' }, objects: [{ ...tampered.objects[0], etag: '"abc123"', versionId: 'v1' }] }; expect(() => serializeUploadReport(wrongKey)).toThrow()
  })

  it('sanitizes cleanup failures and preserves the original readback failure', async () => {
    const makeAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), result.objects.find((object) => args.includes(object.key)).body); return {} }
    const success = await createRun(); const cleanup = await uploadMigrationRun(success.config, { runAws: makeAws, fetch: successFetch(), approvedTarget, fsImpl: { rm: async (path) => { if (path.includes('.t14d-readback-')) throw new Error('raw cleanup path') } } }); expect(cleanup.report.failure).toEqual({ stage: 'cleanup', category: 'readback', key: null }); expect(() => serializeUploadReport(cleanup.report)).not.toThrow(); expect(cleanup.human).not.toContain('raw cleanup path'); await rm(success.runDir, { recursive: true, force: true })
    const original = await createRun(); const preserved = await uploadMigrationRun(original.config, { runAws: async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), 'bad'); throw new Error('raw original') }, fetch: successFetch(), approvedTarget, fsImpl: { rm: async (path) => { if (path.includes('.t14d-readback-')) throw new Error('raw cleanup path') } } }); expect(preserved.report.failure.stage).toBe('readback'); expect(preserved.report.failure.key).toBe(preserved.report.objects[0].key); expect(preserved.human).not.toContain('raw'); await rm(original.runDir, { recursive: true, force: true })
  })

  it('stops after N successful puts on collision with exact prefix metadata', async () => {
    const { runDir, config } = await createRun(); let puts = 0; const calls = []; const runAws = async (args) => { calls.push(args); if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) { puts += 1; if (puts === 2) throw Object.assign(new Error(), { code: 412 }); return { ETag: '"abc123"', VersionId: 'v1' } }; throw new Error('readback forbidden') }; const report = await uploadMigrationRun(config, { runAws, fetch: successFetch(), approvedTarget }); expect(report.report.counts).toEqual({ attempted: 2, uploaded: 1, readback: 0, cloudfront: 0 }); expect(report.report.objects[0].etag).toBe('"abc123"'); expect(report.report.objects[1].etag).toBeNull(); expect(calls.filter((args) => args.includes('get-object'))).toHaveLength(0); await rm(runDir, { recursive: true, force: true })
  })

  it('rejects pending or non-stream CloudFront bodies without unbounded arrayBuffer', async () => {
    const { runDir: pendingDir, config: pendingConfig } = await createRun(); let signal; const pendingAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), result.objects.find((object) => args.includes(object.key)).body); return {} }; const pendingBody = new ReadableStream({ start() {}, cancel() { return Promise.reject(new Error('cancel failure')) } }); const pending = await uploadMigrationRun({ ...pendingConfig, timeoutMs: 10, maxAttempts: 1 }, { runAws: pendingAws, fetch: async (_url, options) => { signal = options.signal; return new Response(pendingBody, { status: 200, headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60' } }) }, approvedTarget }); expect(pending.report.failure.category).toBe('timeout'); expect(signal?.aborted).toBe(true); await rm(pendingDir, { recursive: true, force: true })
    const { runDir: plainDir, config: plainConfig } = await createRun(); const plain = await uploadMigrationRun({ ...plainConfig, maxAttempts: 1 }, { runAws: pendingAws, fetch: async () => ({ status: 200, headers: new Headers({ 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60' }), arrayBuffer: async () => new Uint8Array(1 << 20) }), approvedTarget }); expect(plain.report.failure.stage).toBe('cloudfront'); expect(plain.report.failure.key).toBe(result.objects[0].key); await rm(plainDir, { recursive: true, force: true })
  })

  it('bounds CloudFront retries and settles pending fetches without AWS fallback', async () => {
    const { runDir: retryDir, config: retryConfig } = await createRun(); let fetchCalls = 0; const runAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), result.objects.find((object) => args.includes(object.key)).body); return {} }; const retryFetch = async (url) => { fetchCalls += 1; if (fetchCalls % 2 === 1) return new Response('', { status: 503 }); return new Response(body(result.objects.find((object) => url.endsWith(object.key))), { status: 200, headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60' } }) }; const retried = await uploadMigrationRun(retryConfig, { runAws, fetch: retryFetch, approvedTarget }); expect(retried.report.status).toBe('match'); expect(fetchCalls).toBe(8); await rm(retryDir, { recursive: true, force: true })
    const { runDir: timeoutDir, config: timeoutConfig } = await createRun(); const timed = await uploadMigrationRun({ ...timeoutConfig, maxAttempts: 1, timeoutMs: 5 }, { runAws, fetch: () => new Promise(() => {}), approvedTarget }); expect(timed.report.failure.category).toBe('timeout'); expect(timed.report.counts.cloudfront).toBe(0); await rm(timeoutDir, { recursive: true, force: true })
  })

  it('strictly validates CloudFront MIME, directives, Age, streaming bounds, and current-key failures', async () => {
    const variants = [
      { 'content-type': 'application/jsonx', 'cache-control': 'public, max-age=0, s-maxage=60' },
      { 'content-type': 'application/json', 'cache-control': 'public, max-age=00, s-maxage=60' },
      { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=61' },
      { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60', age: '61' },
      { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60', age: 'x' }
    ]
    for (const headers of variants) {
      const { runDir, config } = await createRun(); const calls = []; const runAws = async (args) => { calls.push(args); if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), result.objects.find((object) => args.includes(object.key)).body); return {} }; const checked = await uploadMigrationRun(config, { runAws, fetch: async (url) => new Response(body(result.objects[0]), { status: 200, headers }), approvedTarget }); expect(checked.report.failure.stage).toBe('cloudfront'); expect(checked.report.failure.key).toBe(result.objects[0].key); expect(checked.report.counts.cloudfront).toBe(0); expect(calls.filter((args) => args.includes('get-object'))).toHaveLength(4); await rm(runDir, { recursive: true, force: true })
    }
    const { runDir: streamDir, config: streamConfig } = await createRun(); const streamRunAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), result.objects.find((object) => args.includes(object.key)).body); return {} }; const stream = new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode('{')); controller.enqueue(new TextEncoder().encode('"bad":true}')); controller.close() } }); const streamed = await uploadMigrationRun(streamConfig, { runAws: streamRunAws, fetch: async () => new Response(stream, { status: 200, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'public, max-age=0, s-maxage=60' } }), approvedTarget }); expect(streamed.report.failure.stage).toBe('cloudfront'); expect(streamed.report.failure.key).toBe(result.objects[0].key); await rm(streamDir, { recursive: true, force: true })
    const { runDir: overDir, config: overConfig } = await createRun(); const overRunAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), result.objects.find((object) => args.includes(object.key)).body); return {} }; const oversized = await uploadMigrationRun({ ...overConfig, maxAttempts: 1 }, { runAws: overRunAws, fetch: async () => new Response(new Uint8Array(32769), { status: 200, headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60' } }), approvedTarget }); expect(oversized.report.failure.stage).toBe('cloudfront'); expect(oversized.report.failure.key).toBe(result.objects[0].key); await rm(overDir, { recursive: true, force: true })
    const { runDir: deadlineDir, config: deadlineConfig } = await createRun(); let deadlineCalls = 0; const deadlineRunAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; await writeFile(args.at(-1), result.objects.find((object) => args.includes(object.key)).body); return {} }; const deadlineFetch = async () => { deadlineCalls += 1; if (deadlineCalls === 1) return new Response('', { status: 503 }); return new Promise(() => {}) }; const deadline = await uploadMigrationRun({ ...deadlineConfig, timeoutMs: 20, maxAttempts: 4 }, { runAws: deadlineRunAws, fetch: deadlineFetch, approvedTarget }); expect(deadline.report.failure.category).toBe('timeout'); expect(deadlineCalls).toBe(2); await rm(deadlineDir, { recursive: true, force: true })
  })

  it('seals the accepted 74-object run with exact files and reread hashes', async () => {
    const source = resolve('.artifacts/migration/t14e-transform'); expect(existsSync(join(source, 'manifest.json'))).toBe(true)
    const parent = await mkdtemp(join(tmpdir(), 't14f-seal-')); const target = join(parent, 'sealed'); const sealed = await sealUploadRun({ sourceDir: source, targetDir: target }); expect(sealed.objectCount).toBe(74)
    const files = []; const walk = async (path) => { for (const entry of await readdir(path, { withFileTypes: true })) { const child = join(path, entry.name); if (entry.isDirectory()) await walk(child); else files.push(child.slice(target.length + 1)) } }; await walk(target)
    expect(files).toHaveLength(75); expect(files).toContain('manifest.json'); expect(files.some((file) => file.includes('capture') || file.includes('comparison') || file.includes('credential'))).toBe(false); await rm(parent, { recursive: true, force: true })
  })

  it('rejects sealed manifest/hash/extra target inputs before writing', async () => {
    const source = resolve('.artifacts/migration/t14e-transform'); const parent = await mkdtemp(join(tmpdir(), 't14f-seal-invalid-')); const target = join(parent, 'sealed'); const badSource = join(parent, 'bad-source'); await mkdir(badSource); await writeFile(join(badSource, 'manifest.json'), '{}')
    await expect(sealUploadRun({ sourceDir: badSource, targetDir: target })).rejects.toThrow(); expect(existsSync(target)).toBe(false); await expect(sealUploadRun({ sourceDir: source, targetDir: target })).resolves.toMatchObject({ objectCount: 74 }); await expect(sealUploadRun({ sourceDir: source, targetDir: target })).rejects.toThrow(); await rm(parent, { recursive: true, force: true })
  })

  it('builds exact head-object args and writes reports atomically without raw data', async () => {
    const config = { ...baseConfig, runDir: '/safe/run', manifestPath: '/safe/run/manifest.json' }; const key = result.objects[0].key; expect(headObjectArgs(config, key)).toEqual(['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 's3api', 'head-object', '--bucket', bucket, '--key', key]); expect(() => headObjectArgs(config, '../secret')).toThrow()
    const artifacts = { objects: result.objects.map(({ body, ...object }) => object), manifest: result.manifest, manifestBytes: result.manifestBytes }; const absent = await preflightSealedAbsence(config, artifacts, async (args) => { expect(args).toContain('head-object'); const error = new Error(); error.code = 404; throw error }); expect(absent).toEqual({ objectCount: result.objects.length, allAbsent: true })
    const report = { schemaVersion: 1, status: 'mismatch', counts: { attempted: 0, uploaded: 0, readback: 0, cloudfront: 0 }, objects: [], failure: { stage: 'preflight', category: 'preflight', key: null } }; const parent = await mkdtemp(join(tmpdir(), 't14f-report-')); const reportDir = join(parent, 'report'); await expect(writeUploadReports(report, reportDir)).resolves.toBe(reportDir); expect(JSON.parse(await readFile(join(reportDir, 'report.json'), 'utf8'))).toEqual(report); expect(await readFile(join(reportDir, 'report.txt'), 'utf8')).not.toMatch(/body|credential|path|secret/i); await expect(writeUploadReports(report, reportDir)).rejects.toThrow(); await rm(parent, { recursive: true, force: true })
  })

  it('uses execFile argument arrays with bounded JSON output and no shell', async () => {
    const calls = []; const value = await runAwsJson((file, args, options, callback) => { calls.push({ file, args, options }); callback(null, '{"Account":"470447451992"}', '') }, ['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 'sts', 'get-caller-identity'], { env: { PATH: '/bin', HOME: '/tmp', AWS_SECRET_ACCESS_KEY: 'secret', AWS_ENDPOINT_URL: 'https://evil' } }); expect(value).toEqual({ Account: '470447451992' }); expect(calls[0].file).toBe('aws'); expect(calls[0].options.shell).toBe(false); expect(calls[0].options.env).toEqual({ PATH: '/bin', HOME: '/tmp' }); expect(calls[0].args).toEqual(['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 'sts', 'get-caller-identity'])
    await expect(runAwsJson((_file, _args, _options, callback) => callback(null, 'x'.repeat(100), ''), ['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 'sts', 'get-caller-identity'], { maxOutputBytes: 10 })).rejects.toThrow(); await expect(runAwsJson((_file, _args, _options, callback) => callback(Object.assign(new Error(), { code: 254 }), '', 'raw principal'), ['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 'sts', 'get-caller-identity'])).rejects.toThrow(/command/)
    const head = ['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 's3api', 'head-object', '--bucket', bucket, '--key', result.objects[0].key]
    await expect(runAwsJson(() => {}, [...head, '--extra', 'value'])).rejects.toThrow(/command/)
    await expect(runAwsJson(() => {}, head.map((value) => value === bucket ? 'other-bucket' : value))).rejects.toThrow(/command/)
    const put = [...head.slice(0, 6), 's3api', 'put-object', '--bucket', bucket, '--key', result.objects[0].key, '--body', '/safe/body.json', '--content-type', 'application/json', '--cache-control', 'public, max-age=0, s-maxage=60']
    await expect(runAwsJson(() => {}, put)).rejects.toThrow(/command/)
    const validPut = [...put, '--if-none-match', '*']; const callbackAws = (_file, _args, _options, callback) => callback(null, '{}', ''); await expect(runAwsJson(callbackAws, validPut, { roots: { sealedRoot: '/safe', readbackRoot: '/safe' } })).resolves.toEqual({}); await expect(runAwsJson(callbackAws, validPut, { roots: { sealedRoot: '/other', readbackRoot: '/safe' } })).rejects.toThrow(/path/)
  })

  it('preflights the fixed executable without accepting symlinks or non-executables', async () => {
    const base = { isFile: () => true, isSymbolicLink: () => false, mode: 0o755 }; await expect(preflightAwsExecutable({ lstat: async () => base, realpath: async () => '/usr/local/aws-cli/aws' })).resolves.toBe('/usr/local/aws-cli/aws'); await expect(preflightAwsExecutable({ lstat: async () => ({ ...base, isSymbolicLink: () => true }), realpath: async () => '/usr/local/aws-cli/aws' })).rejects.toThrow(); await expect(preflightAwsExecutable({ lstat: async () => ({ ...base, mode: 0o644 }), realpath: async () => '/usr/local/aws-cli/aws' })).rejects.toThrow(); await expect(preflightAwsExecutable({ lstat: async () => base, realpath: async () => '/outside/aws' })).rejects.toThrow()
    await expect(preflightAwsExecutable({ lstat, realpath })).resolves.toBe('/usr/local/aws-cli/aws')
  })

  it('classifies AWS CLI 254 service errors without exposing stderr', async () => {
    const args = ['--profile', 'codex-prod', '--region', 'ap-northeast-1', '--output', 'json', 's3api', 'head-object', '--bucket', bucket, '--key', result.objects[0].key]
    const notFound = Object.assign(new Error(), { code: 254 }); await expect(runAwsJson((_file, _args, _options, callback) => callback(notFound, '', 'An error occurred (404) when calling the HeadObject operation: Not Found'), args)).rejects.toMatchObject({ serviceCode: 'NotFound' })
    const denied = Object.assign(new Error(), { code: 254 }); await expect(runAwsJson((_file, _args, _options, callback) => callback(denied, '', 'An error occurred (403) when calling the HeadObject operation: AccessDenied'), args)).rejects.toMatchObject({ serviceCode: 'AccessDenied' })
    const hostileNotFound = Object.assign(new Error(), { code: 254 }); await expect(runAwsJson((_file, _args, _options, callback) => callback(hostileNotFound, '', 'An error occurred (403) when calling the HeadObject operation: AccessDenied for principal NotFound'), args)).rejects.toMatchObject({ serviceCode: 'AccessDenied' })
    const wrongOperation = Object.assign(new Error(), { code: 254 }); await expect(runAwsJson((_file, _args, _options, callback) => callback(wrongOperation, '', 'An error occurred (404) when calling the PutObject operation: Not Found'), args)).rejects.toMatchObject({ serviceCode: 'Other' })
    const putArgs = [...args.slice(0, 6), 's3api', 'put-object', '--bucket', bucket, '--key', result.objects[0].key, '--body', '/safe/body.json', '--content-type', 'application/json', '--cache-control', 'public, max-age=0, s-maxage=60', '--if-none-match', '*']
    const collision = Object.assign(new Error(), { code: 254 }); await expect(runAwsJson((_file, _args, _options, callback) => callback(collision, '', 'An error occurred (412) when calling the PutObject operation: PreconditionFailed'), putArgs)).rejects.toMatchObject({ serviceCode: 'Collision' })
    await expect(preflightSealedAbsence({ ...baseConfig }, { objects: [{ key: result.objects[0].key }] }, async () => { throw Object.assign(new Error(), { serviceCode: 'AccessDenied' }) })).rejects.toThrow(/preflight/)
  })

  it('keeps the fixed Node24 CLI boundary offline for help and invalid targets', async () => {
    expect(parseUploadCliArgs(['--help'])).toEqual({ help: true }); expect(() => parseUploadCliArgs(['--run', 'x', '--bucket', 'other'])).toThrow(); expect(() => parseUploadCliArgs(['--run', '../sealed', '--report', 'report'])).toThrow(); expect(() => parseUploadCliArgs(['--run', '-sealed', '--report', 'report'])).toThrow()
    let calls = 0; const deps = { cwd: '/tmp/itsrun', runAws: async () => { calls += 1 }, fetch: async () => { calls += 1 } }
    await expect(uploadCliMain(['--help'], {}, deps)).resolves.toBe(0); await expect(uploadCliMain(['--run', '/outside', '--report', '/outside-report'], {}, deps)).resolves.toBe(2); for (const key of ['AWS_PROFILE', 'AWS_ENDPOINT_URL', 'AWS_SHARED_CREDENTIALS_FILE', 'AWS_CONFIG_FILE', 'AWS_REGION', 'AWS_ROLE_ARN', 'AWS_WEB_IDENTITY_TOKEN_FILE', 'AWS_CA_BUNDLE']) await expect(uploadCliMain(['--run', 'sealed', '--report', 'report'], { [key]: 'alternate' }, deps)).resolves.toBe(2); expect(calls).toBe(0)
  })

  it('rejects CLI artifact-root symlink escape before injected AWS or fetch', async () => {
    const workspace = await mkdtemp(join(tmpdir(), 't14f-cli-root-')); const outside = await mkdtemp(join(tmpdir(), 't14f-cli-out-')); await mkdir(join(outside, 'migration', 'sealed'), { recursive: true }); await symlink(join(outside, 'migration'), join(workspace, '.artifacts')); let calls = 0
    const result = await uploadCliMain(['--run', 'sealed', '--report', 'report'], {}, { cwd: workspace, runAws: async () => { calls += 1 }, fetch: async () => { calls += 1 } }); expect(result).toBe(2); expect(calls).toBe(0); await rm(workspace, { recursive: true, force: true }); await rm(outside, { recursive: true, force: true })
  })

  it('runs the fixed CLI boundary end-to-end over all 74 sealed objects with injected AWS/fetch only', async () => {
    const workspace = await mkdtemp(join(tmpdir(), 't14f-cli-e2e-')); const artifactRoot = join(workspace, '.artifacts', 'migration'); await mkdir(artifactRoot, { recursive: true }); const sealedDir = join(artifactRoot, 'sealed'); await sealUploadRun({ sourceDir: resolve('.artifacts/migration/t14e-transform'), targetDir: sealedDir }); const manifest = JSON.parse(await readFile(join(sealedDir, 'manifest.json'))); let sts = 0; let heads = 0; let puts = 0; let gets = 0; let fetches = 0; const calls = []
    const runAws = async (args) => { calls.push(args); if (args.includes('get-caller-identity')) { sts += 1; return { Account: '470447451992' } }; if (args.includes('head-object')) { heads += 1; const error = new Error(); error.code = 254; error.serviceCode = 'NotFound'; throw error }; if (args.includes('put-object')) { puts += 1; return { ETag: '"abc123"', VersionId: `v${puts}` } }; if (args.includes('get-object')) { gets += 1; const key = args[args.indexOf('--key') + 1]; await writeFile(args.at(-1), await readFile(join(sealedDir, key))); return {} }; throw new Error('unexpected') }
    const fetcher = async (url) => { fetches += 1; const key = url.slice(url.indexOf('data/')); return new Response(await readFile(join(sealedDir, key)), { status: 200, headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60', age: '0' } }) }
    await expect(uploadCliMain(['--run', 'sealed', '--report', 'report'], {}, { cwd: workspace, runAws, fetch: fetcher })).resolves.toBe(0); expect({ sts, heads, puts, gets, fetches }).toEqual({ sts: 1, heads: 74, puts: 74, gets: 74, fetches: 74 }); expect(JSON.parse(await readFile(join(artifactRoot, 'report', 'report.json'))).status).toBe('match'); expect(calls.findIndex((args) => args.includes('put-object'))).toBeGreaterThan(calls.map((args, index) => args.includes('head-object') ? index : -1).sort((a, b) => b - a)[0])
    let collisionPuts = 0; let collisionGets = 0; let collisionFetches = 0; const collisionAws = async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('head-object')) { const error = new Error(); error.code = 254; error.serviceCode = 'NotFound'; throw error }; if (args.includes('put-object')) { collisionPuts += 1; throw Object.assign(new Error(), { code: 254, serviceCode: 'Collision' }) }; if (args.includes('get-object')) collisionGets += 1; return {} }; await expect(uploadCliMain(['--run', 'sealed', '--report', 'collision-report'], {}, { cwd: workspace, runAws: collisionAws, fetch: async () => { collisionFetches += 1 } })).resolves.toBe(2); const collisionReport = JSON.parse(await readFile(join(artifactRoot, 'collision-report', 'report.json'))); expect(collisionReport.failure).toMatchObject({ stage: 'upload', category: 'collision', key: manifest.objects[0].key }); expect({ collisionPuts, collisionGets, collisionFetches }).toEqual({ collisionPuts: 1, collisionGets: 0, collisionFetches: 0 }); await rm(workspace, { recursive: true, force: true })
  })

  it('requires all 74 exact heads absent before any put and preserves deterministic order', async () => {
    const source = resolve('.artifacts/migration/t14e-transform'); const parent = await mkdtemp(join(tmpdir(), 't14f-74-')); const sealedDir = join(parent, 'sealed'); await sealUploadRun({ sourceDir: source, targetDir: sealedDir }); const manifest = JSON.parse(await readFile(join(sealedDir, 'manifest.json'))); const config = { profile: 'codex-prod', account: '470447451992', region: 'ap-northeast-1', bucket, distributionDomain: 'preview.example.test', manifestSha256: '2d6000e0a56026abc1bdad91717d4627d942b6cef2d19e729239c5192000eb16', objectCount: 74, allowedPrefix: 'data/v1/stadiums/', runDir: sealedDir, manifestPath: join(sealedDir, 'manifest.json'), maxAttempts: 1, timeoutMs: 100 }; const approved = { bucket, distributionDomain: 'preview.example.test' }; const calls = []; const runAws = async (args) => { calls.push(args); if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('head-object')) { const error = new Error(); error.code = 254; error.serviceCode = 'NotFound'; throw error }; if (args.includes('put-object')) return { ETag: '"abc123"', VersionId: 'v1' }; if (args.includes('get-object')) { const key = args[args.indexOf('--key') + 1]; await writeFile(args.at(-1), await readFile(join(sealedDir, key))); return {} }; throw new Error('forbidden command') }; const fetcher = async (url) => { const key = url.slice(url.indexOf('data/')); const data = await readFile(join(sealedDir, key)); return new Response(data, { status: 200, headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=0, s-maxage=60', age: '0' } }) }
    const success = await uploadSealedMigrationRun(config, { runAws, fetch: fetcher, approvedTarget: approved }); expect(success.report.status).toBe('match'); expect(success.report.counts).toEqual({ attempted: 74, uploaded: 74, readback: 74, cloudfront: 74 }); const headCalls = calls.filter((args) => args.includes('head-object')); const putCalls = calls.filter((args) => args.includes('put-object')); expect(calls.filter((args) => args.includes('get-caller-identity'))).toHaveLength(1); expect(headCalls).toHaveLength(74); expect(putCalls).toHaveLength(74); expect(headCalls.map((args) => args[args.indexOf('--key') + 1])).toEqual(manifest.objects.map((object) => object.key)); const firstPut = calls.findIndex((args) => args.includes('put-object')); const lastHead = calls.map((args, index) => args.includes('head-object') ? index : -1).sort((a, b) => b - a)[0]; expect(firstPut).toBeGreaterThan(lastHead); expect(calls.slice(firstPut).some((args) => args.includes('head-object'))).toBe(false)
    let preflightCalls = 0; await writeFile(join(sealedDir, 'extra.txt'), 'extra'); const extra = await uploadSealedMigrationRun(config, { runAws: async () => { preflightCalls += 1; throw new Error('must not call') }, fetch: fetcher, approvedTarget: approved }); expect(extra.report.failure.stage).toBe('preflight'); expect(preflightCalls).toBe(0); await rm(join(sealedDir, 'extra.txt'))
    const bodyPath = join(sealedDir, manifest.objects[0].key); const outsideBody = join(parent, 'outside-body'); await writeFile(outsideBody, await readFile(bodyPath)); await rm(bodyPath); await symlink(outsideBody, bodyPath); const linked = await uploadSealedMigrationRun(config, { runAws: async () => { preflightCalls += 1; throw new Error('must not call') }, fetch: fetcher, approvedTarget: approved }); expect(linked.report.failure.stage).toBe('preflight'); expect(preflightCalls).toBe(0); await rm(bodyPath); await writeFile(bodyPath, await readFile(outsideBody))
    const manifestPath = join(sealedDir, 'manifest.json'); const outsideManifest = join(parent, 'outside-manifest'); await writeFile(outsideManifest, await readFile(manifestPath)); await rm(manifestPath); await symlink(outsideManifest, manifestPath); const linkedManifest = await uploadSealedMigrationRun(config, { runAws: async () => { preflightCalls += 1; throw new Error('must not call') }, fetch: fetcher, approvedTarget: approved }); expect(linkedManifest.report.failure.stage).toBe('preflight'); expect(preflightCalls).toBe(0); await rm(manifestPath); await writeFile(manifestPath, await readFile(outsideManifest))
    const originalBody = await readFile(bodyPath); await writeFile(bodyPath, Buffer.from('tampered')); const tamperedBody = await uploadSealedMigrationRun(config, { runAws: async () => { preflightCalls += 1; throw new Error('must not call') }, fetch: fetcher, approvedTarget: approved }); expect(tamperedBody.report.failure.stage).toBe('preflight'); expect(preflightCalls).toBe(0); await writeFile(bodyPath, originalBody)
    for (const failIndex of [0, 36, 73]) { let heads = 0; let puts = 0; const failed = await uploadSealedMigrationRun(config, { runAws: async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('head-object')) { const index = heads++; if (index === failIndex) { const error = new Error(); error.code = 254; error.serviceCode = 'AccessDenied'; throw error }; const error = new Error(); error.code = 254; error.serviceCode = 'NotFound'; throw error }; if (args.includes('put-object')) { puts += 1; return { ETag: '"abc123"', VersionId: 'v1' } }; throw new Error('must not continue') }, fetch: fetcher, approvedTarget: approved }); expect(failed.report.failure.stage).toBe('preflight'); expect(failed.report.counts).toEqual({ attempted: 0, uploaded: 0, readback: 0, cloudfront: 0 }); expect(puts).toBe(0); expect(heads).toBe(failIndex + 1) }
    for (const mode of ['present', 'malformed']) for (const failIndex of [0, 36, 73]) { let heads = 0; let puts = 0; const failed = await uploadSealedMigrationRun(config, { runAws: async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('head-object')) { const index = heads++; if (index === failIndex) return mode === 'present' ? {} : []; const error = new Error(); error.code = 254; error.serviceCode = 'NotFound'; throw error }; if (args.includes('put-object')) { puts += 1; return { ETag: '"abc123"', VersionId: 'v1' } }; throw new Error('must not continue') }, fetch: fetcher, approvedTarget: approved }); expect(failed.report.failure.stage).toBe('preflight'); expect(failed.report.counts).toEqual({ attempted: 0, uploaded: 0, readback: 0, cloudfront: 0 }); expect(puts).toBe(0); expect(heads).toBe(failIndex + 1) }
    let stsHeads = 0; let stsPuts = 0; const stsMismatch = await uploadSealedMigrationRun(config, { runAws: async (args) => { if (args.includes('get-caller-identity')) return { Account: 'wrong' }; if (args.includes('head-object')) stsHeads += 1; if (args.includes('put-object')) stsPuts += 1; return {} }, fetch: fetcher, approvedTarget: approved }); expect(stsMismatch.report.failure.stage).toBe('sts'); expect(stsHeads).toBe(0); expect(stsPuts).toBe(0)
    let collisionPuts = 0; let collisionReads = 0; let collisionFetches = 0; const collisionRun = await uploadSealedMigrationRun(config, { runAws: async (args) => { if (args.includes('get-caller-identity')) return { Account: '470447451992' }; if (args.includes('head-object')) { const error = new Error(); error.code = 254; error.serviceCode = 'NotFound'; throw error }; if (args.includes('put-object')) { collisionPuts += 1; throw Object.assign(new Error('raw collision stderr'), { code: 254, serviceCode: 'Collision' }) }; if (args.includes('get-object')) collisionReads += 1; return {} }, fetch: async () => { collisionFetches += 1; return fetcher() }, approvedTarget: approved }); expect(collisionRun.report.failure).toEqual({ stage: 'upload', category: 'collision', key: manifest.objects[0].key }); expect(collisionPuts).toBe(1); expect(collisionReads).toBe(0); expect(collisionFetches).toBe(0); expect(JSON.stringify(collisionRun.report)).not.toContain('raw collision stderr')
    await rm(parent, { recursive: true, force: true })
  })
})
